edition = "2021"
unstable_features = true
blank_lines_lower_bound = 1
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
empty_item_single_line = false
force_multiline_blocks = true
format_code_in_doc_comments = true
hex_literal_case = "Upper"
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = false
reorder_impl_items = true
group_imports = "StdExternalCrate"
struct_lit_single_line = false
use_field_init_shorthand = true
